### ISSUE TITLE
Creación de diseño UI/UX de la sección >> Stock de articulos

### ISSUE THREAD

**Issue by FI-UAEMex** [Facultad-Ingenieria-UAEMex/ecommerce#2]
- En figma, crear el diseño UI/UX de la vista de stock -> agregar info y link a la documentación del README.md en <FFONTEND>.
- <BACKEND> Crear proyecto.
- <FRONTEND>Crear proyecto.

**Comment by Rene-Mayhrem** [comment]
Tarea completa
- Se creó un proyecto en Figma
- Se creó la primer vista del stock de artículos
